apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      automountServiceAccountToken: false
      containers:
        - name: user-service
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
          image: ghcr.io/nebengjek/user-service:latest
          ports:
            - containerPort: 9000
          imagePullPolicy: Always
